<?php 
    return [
        'Pending' => 'bg-light-secondary',
        'Approved' => 'bg-light-blue',
        '6.Approved' => 'bg-light-blue',
        'Rejected' => 'bg-light-danger',
        '7.Rejected' => 'bg-light-danger',
        'Fake' => 'bg-light-red',
        '8.Fake' => 'bg-light-red',
        'Return to sender' => 'bg-light-warning',
        '9.Returned to Sender' => 'bg-light-warning',
        'Under discussion' => 'bg-light-info',
        '3.Under Discussion' => 'bg-light-info',
        'Authentication pending' => 'bg-light-orange',
        'Ready for authentication' => 'bg-light-cyan',
        '4.Authentication in Progress' => 'bg-light-cyan',
        'Authentication completed' => 'bg-light-pink',
        '5.Authentication Completed' => 'bg-light-pink',
        'Payment Completed' => 'bg-light-success',
        '10.Payment Completed' => 'bg-light-success',
        'Label Sent' => 'bg-light-pink-dark',
        '1.Label Sent' => 'bg-light-pink-dark',
        'Delivered' => 'bg-light-primary',
        '2.Item Received/Delivered' => 'bg-light-primary',
        'Incoming Sent' => 'bg-light-blue-light',
    ];